services:
  - type: web
    name: sfis-quant-course
    runtime: python
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:server --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
